# Generated by Django 4.0.1 on 2022-03-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(max_length=30)),
                ('text', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(default='default.jpg', upload_to='photos/')),
                ('url', models.CharField(blank=True, max_length=30)),
                ('text_url', models.CharField(max_length=20)),
            ],
        ),
    ]
