# Generated by Django 4.0.1 on 2022-04-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider_content',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='photos/slider/'),
        ),
    ]
