# Generated by Django 4.0.1 on 2022-03-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productinorder_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='price_per_item',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='total_amount',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
