# Generated by Django 4.0.1 on 2022-03-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_productinorder_price_per_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
