# Generated by Django 4.0.1 on 2022-03-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_productinorder_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='price_per_item',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
