# Generated by Django 4.0.1 on 2022-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_productinorder_price_per_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=800)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
