# Generated by Django 4.0.1 on 2022-03-18 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('case', 'Case'), ('cable', 'Cable'), ('other', 'Other')], max_length=10)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('price', models.PositiveIntegerField(default=0, null=True)),
                ('old_price', models.PositiveIntegerField(blank=True, default=0, help_text='Ввод старой цены для отображения скидки на аксесуар', null=True)),
                ('append_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='append_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Ввод старой цены для отображения скидки на товар', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('iPhone', 'iPhone'), ('iPad', 'iPad'), ('iMac', 'iMac'), ('Airpods', 'Airpods')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IMAGE', to='products.product'),
        ),
        migrations.CreateModel(
            name='AccessoriesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('accessory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IMAGE', to='products.accessories')),
            ],
        ),
        migrations.AddField(
            model_name='accessories',
            name='for_product',
            field=models.ManyToManyField(null=True, related_name='Accs', to='products.Product'),
        ),
    ]
