# Generated by Django 4.0.1 on 2022-03-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_accessories_product_append_date_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='for_product',
            field=models.ManyToManyField(related_name='Accs', to='products.Product'),
        ),
    ]
