# Generated by Django 4.0.1 on 2022-04-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_slug_delete_accessoriesimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, verbose_name='URL'),
        ),
    ]
