# Generated by Django 4.0.1 on 2022-04-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('iPhone', 'iPhone'), ('iPad', 'iPad'), ('Mac', 'Mac'), ('Airpods', 'Airpods')], default=None, max_length=10, null=True),
        ),
    ]
