# Generated by Django 4.0.1 on 2022-04-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
