# Generated by Django 4.0.1 on 2022-04-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='availability',
            field=models.CharField(choices=[('In', 'In stock'), ('Out', 'Out stock')], default='In stock', max_length=50),
        ),
    ]
