# Generated by Django 4.0.1 on 2022-04-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_accessories_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
    ]
