# Generated by Django 4.0.1 on 2022-04-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('In', 'In stock'), ('Out', 'Out stock')], default='In stock', max_length=10),
        ),
    ]
